export const DATA = [
  {
    label: 'label',
    title: 'title',
    description: 'description',
    level: '초급',
    classroom: 'classroom',
    duration: 'duration',
    price: '무료',
  },
  {
    label: 'label',
    title: 'title',
    description: 'description',
    level: '초급',
    classroom: 'classroom',
    duration: 'duration',
    price: '무료',
  },
  {
    label: 'label',
    title: 'title',
    description: 'description',
    level: '초급',
    classroom: 'classroom',
    duration: 'duration',
    price: '무료',
  },
  {
    label: 'label',
    title: 'title',
    description: 'description',
    level: '초급',
    classroom: 'classroom',
    duration: 'duration',
    price: '무료',
  },
  {
    label: 'label',
    title: 'title',
    description: 'description',
    level: '초급',
    classroom: 'classroom',
    duration: 'duration',
    price: '무료',
  },
];
